### PR TITLE
fix: compatibility with the latest Tauri release

### PR DESCRIPTION
**Pull request by flerouwu**
## Issue
Currently, `tauri-controls` doesn't work with the latest versions of `@tauri-apps/plugin-window` due to a [refactor.](https://github.com/tauri-apps/plugins-workspace/pull/426).

### Links
- [feat(window): refactor and improvements](https://github.com/tauri-apps/plugins-workspace/pull/426)
- [window v2.0.0-alpha.1](https://github.com/tauri-apps/plugins-workspace/releases/tag/window-v2.0.0-alpha.1)

## Solution
Bumping each package's version of `@tauri-apps/plugin-window` to `2.0.0-alpha.1`, as well as modifying code to adjust for the refactor has fixed this issue.

## Notes
- The Solid and Vue packages have had their `ref()` and `createSignal()` function calls removed respectively, as they are no longer required.

### CODE REVIEW

**Comment by agmmnn** [comment]
Thanks for the PR. 🙏

> Currently, `tauri-controls` doesn't work with the latest versions of `@tauri-apps/plugin-window` due to a [refactor.](https://github.com/tauri-apps/plugins-workspace/pull/426).

Yes, I was planning to work on it, but I was on vacation and just got back.

**Comment by flerouwu** [comment]
> Thanks for the PR. 🙏
> 
> > Currently, `tauri-controls` doesn't work with the latest versions of `@tauri-apps/plugin-window` due to a [refactor.](https://github.com/tauri-apps/plugins-workspace/pull/426).
> 
> Yes, I was planning to work on it, but I was on vacation and just got back.

All good! Hope you enjoyed your vacation!

Hope this PR helps. Feel free to take your time reviewing it.

**Comment by agmmnn** [comment]
I'll look into it, but I'm stuck with this issue on Windows. I can only move forward if this problem is fixed. :/

https://github.com/tauri-apps/tauri/issues/7784
https://discord.com/channels/616186924390023171/1149396631070982274

**Comment by agmmnn** [comment]
Related issues: #13

**Comment by agmmnn** [comment]
> I'll look into it, but I'm stuck with this issue on Windows. I can only move forward if this problem is fixed. :/
> 
> [tauri-apps/tauri#7784](https://github.com/tauri-apps/tauri/issues/7784) [discord.com/channels/616186924390023171/1149396631070982274](https://discord.com/channels/616186924390023171/1149396631070982274)

https://github.com/tauri-apps/tauri/issues/7801
https://github.com/tauri-apps/tauri/releases/tag/tauri-v2.0.0-alpha.14

**Pull request merged**
