### PR TITLE
Added support for `next` tauri

### PR DESCRIPTION
**Pull request by annie444**
Window api now in @tauri-apps/api

### CODE REVIEW

**Comment by agmmnn** [comment]
Thank you. 🙏 This update on my mind but I don't have much time lately.

I'll check the PR. The only thing that caught my eye was the vite.mjs files are included.

**Comment by agmmnn** [comment]
> Window api now in @tauri-apps/api

Reference: https://github.com/tauri-apps/tauri/releases/tag/tauri-v2.0.0-alpha.16

**Comment by annie444** [comment]
It appears that the gitignore needs to be updated. Let me clear the cache and push an updated version. The next push should be clean of generated files.

**Comment by annie444** [comment]
Done!

**Comment by annie444** [comment]
Wait I haven't cleared out the cache...

**Comment by annie444** [comment]
So the issue with the vite mjs files was with my home server. There was just an issue with conflicting timestamps when syncing with the server causing a backup file being made. I removed it and everything should be good to merge now!

**Pull request merged**
